### ISSUE TITLE
Sorry not an Issue, Just a question

### ISSUE THREAD

**Issue by Gamedevolop** [whscienceteacher/whscienceteacher.github.io#1]
Hi 

Thank you for sharing with us these Awesome apps

I always wanted to learn physics, could you provide the Construct Capx so I can have a look at the Math involved how was done so I can understand the Physics Math better? 
As it's very difficult to learn from just the website test 

Thanks  a lot in advance keep up the good work

**Comment by whscienceteacher** [comment]
Is there a particular one of the apps you wanted to see?

**Comment by Gamedevolop** [comment]
Yes please the Roller coaster 
https://whscience.org/rollercoastermotion/

Thank you 

I love that you can change the High and the Angle of the roller coaster and how it impacts the speed and how far can travel, that's why I would love to see all the calculations that go behind the code, also if the Roller coaster uses physics behaviour or its a customer made physics and how the Roller coaster moves smoothly on the road even on the round turns.
 
A lot of things I would love to see actually

**Comment by Gamedevolop** [comment]
Hi
I'm just checking if Is going to be possible to check the source code or not?
Thank you

**Comment by whscienceteacher** [comment]
There are some issues with that. Can you send me an email at whscienceteacher@outlook.com to discuss?

**Comment by Gamedevolop** [comment]
Thanks a lot

Email sent 

Also, I will close this as its not a bug sorry for that
